name: Liquibase Workflow

on:
  push:
    branches:
      - main

jobs:
  liquibase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
        id: setup-java

      - name: Run Liquibase Update
        env:
          LIQUIBASE_URL: "jdbc:sqlserver://52.140.6.193;hary_test=HR;encrypt=true;trustServerCertificate=true;"
          LIQUIBASE_USERNAME: "sa"
          LIQUIBASE_PASSWORD: "Trilok@786"
          LIQUIBASE_CHANGELOG: 'liquibase_demo/changelog.sql'
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/liquibase_demo:/liquibase/changelog \
            -v ${{ github.workspace }}/liquibase_demo/mssql-jdbc-12.7.0.jre11-preview.jar:/liquibase/mssql-jdbc-12.7.0.jre11-preview.jar \
            liquibase/liquibase:latest \
            --url=$LIQUIBASE_URL \
            --username=$LIQUIBASE_USERNAME \
            --password=$LIQUIBASE_PASSWORD \
            --changeLogFile=$LIQUIBASE_CHANGELOG \
            --classpath=/liquibase/mssql-jdbc-12.7.0.jre11-preview.jar \
            update
