name: Liquibase Workflow
on:
  push:
    branches:
      - main

jobs:
  liquibase:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v2
      - name  : Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
          
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
        id: setup-java

      # - name: Run Liquibase Update
      #   env:
      #     LIQUIBASE_URL: "jdbc:sqlserver://52.140.6.193;databaseName=hary_test;encrypt=true;trustServerCertificate=true;"
      #     LIQUIBASE_USERNAME: "sa"
      #     LIQUIBASE_PASSWORD: "Trilok@786"
      #     LIQUIBASE_CHANGELOG: "/home/runner/work/Liquibase-demo/Liquibase-demo/Liquibase_demo/changelog.sql"
      #   run: |
      #     docker run --rm \
      #       liquibase/liquibase:latest \
      #       --url=$LIQUIBASE_URL \
      #       --username=$LIQUIBASE_USERNAME \
      #       --password=$LIQUIBASE_PASSWORD \
      #       --changeLogFile=/liquibase/changelog.sql \
      #       --classpath=/liquibase/mssql-jdbc-12.7.0.jre11-preview.jar \
      #       update
      - name: Test Database Connection
        run: |
          docker run --rm --network host dperson/freetds \
          tsql -H 52.140.6.193 -p 1433 -U sa -P Trilok@786 -D hary_test -C

      - name: Run Liquibase Update
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/Liquibase_demo:/liquibase/changelog \
            liquibase/liquibase \
            --url="jdbc:sqlserver://52.140.6.193;databaseName=hary_test;encrypt=true;trustServerCertificate=true" \
            --username="sa" \
            --password="Trilok@786" \
            --changeLogFile=/liquibase/changelog/changelog.sql \
            update
