name: Liquibase Workflow
on:
  push:
    branches:
      - main

jobs:
  liquibase:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v2
      - name  : Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
          
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
        id: setup-java

      # - name: Run Liquibase Update
      #   env:
      #     LIQUIBASE_URL: "jdbc:sqlserver://52.140.6.193;databaseName=hary_test;encrypt=true;trustServerCertificate=true;"
      #     LIQUIBASE_USERNAME: "sa"
      #     LIQUIBASE_PASSWORD: "Trilok@786"
      #     LIQUIBASE_CHANGELOG: "/home/runner/work/Liquibase-demo/Liquibase-demo/Liquibase_demo/changelog.sql"
      #   run: |
      #     docker run --rm \
      #       liquibase/liquibase:latest \
      #       --url=$LIQUIBASE_URL \
      #       --username=$LIQUIBASE_USERNAME \
      #       --password=$LIQUIBASE_PASSWORD \
      #       --changeLogFile=/liquibase/changelog.sql \
      #       --classpath=/liquibase/mssql-jdbc-12.7.0.jre11-preview.jar \
      #       update

      # - name: List Files in Mounted Directory
      #   run: |
      #     docker run \
      #       -v ${{ github.workspace }}/liquibase_demo:/liquibase/changelog \
      #       alpine sh -c "ls -R /liquibase/changelog && cat /liquibase/changelog/changelog.sql"

      # - name: Run Liquibase Update
      #   run: |
      #     docker run \
      #       -v ${{ github.workspace }}/liquibase_demo:/liquibase/changelog \
      #       liquibase/liquibase \
      #       --url="jdbc:sqlserver://52.140.6.193;databaseName=hary_test;encrypt=true;trustServerCertificate=true" \
      #       --username="sa" \
      #       --password="Trilok@786" \
      #       --changeLogFile=/liquibase/changelog/changelog.sql \
      #       update
      - name: List Files in Mounted Directory with Alpine
        run: |
          docker run \
            -v ${{ github.workspace }}/liquibase_demo:/liquibase/changelog \
            alpine sh -c "ls -R /liquibase/changelog && cat /liquibase/changelog/changelog.sql"

      - name: List Files in Mounted Directory with Liquibase
        run: |
          docker run \
            -v ${{ github.workspace }}/liquibase_demo:/liquibase/changelog \
            liquibase/liquibase sh -c "ls -R /liquibase/changelog && cat /liquibase/changelog/changelog.sql"
            
      - name: Verify Changelog File in Liquibase Container
        run: |
          docker run \
            -v ${{ github.workspace }}/liquibase_demo:/liquibase/changelog \
            liquibase/liquibase sh -c "if [ -f /liquibase/changelog/changelog.sql ]; then echo 'File exists'; else echo 'File does not exist'; fi"

      - name: Run Liquibase Update
        run: |
          # docker run \
          #   -v ${{ github.workspace }}/liquibase_demo:/liquibase/changelog \
          #   liquibase/liquibase \
          #   --url="jdbc:sqlserver://52.140.6.193;databaseName=hary_test;encrypt=true;trustServerCertificate=true;" \
          #   --username="sa" \
          #   --password="Trilok@786" \
          #   --changeLogFile=/liquibase/changelog/changelog.sql \
          #   update

          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            liquibase/liquibase sh -c "cp /workspace/liquibase_demo/changelog.sql /liquibase/changelog/ \
            ls
            --url='jdbc:sqlserver://52.140.6.193;databaseName=hary_test;encrypt=true;trustServerCertificate=true' \
            --username='sa' \
            --password='Trilok@786' \
            --changeLogFile=/liquibase/changelog/changelog.sql \
            update"
