name: Liquibase Workflow

on:
  push:
    branches:
      - main

jobs:
  liquibase:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v2
      - name  : Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
          
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
        id: setup-java

      - name: Run Liquibase Update
        env:
          LIQUIBASE_URL: "jdbc:sqlserver://52.140.6.193;databaseName=hary_test;encrypt=true;trustServerCertificate=true;"
          LIQUIBASE_USERNAME: "sa"
          LIQUIBASE_PASSWORD: "Trilok@786"
          LIQUIBASE_CHANGELOG: "/home/runner/work/Liquibase-demo/Liquibase-demo/Liquibase_demo/changelog.sql"
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/Liquibase_demo/changelog.sql:/liquibase/changelog.sql \
            -v ${{ github.workspace }}/Liquibase_demo/mssql-jdbc-12.7.0.jre11-preview.jar:/liquibase/mssql-jdbc-12.7.0.jre11-preview.jar \
            liquibase/liquibase:latest \
            --url=$LIQUIBASE_URL \
            --username=$LIQUIBASE_USERNAME \
            --password=$LIQUIBASE_PASSWORD \
            --changeLogFile=/liquibase/changelog.sql \
            --classpath=/liquibase/mssql-jdbc-12.7.0.jre11-preview.jar \
            update
